# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET: ${{secrets.gh_pages}}
      USER_NAME: eamesh
      USER_EMAIL: easeava@gmail.com
      BUILD_PATH: ./dist
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.10.0
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - run: pnpm install
    - run: pnpm build:gh-pages

    - name: Set Script
      run: |
        script='i\
        <script>\
        var _hmt = _hmt || []; \
        (function() {\
          var hm = document.createElement(\"script\"); \
          hm.src = \"https://hm.baidu.com/hm.js?9c778fcbbe17264bf9be0deb42e4533a\"; \
          var s = document.getElementsByTagName(\"script\")[0]; \
          s.parentNode.insertBefore(hm, s); \
        })(); \
        </script>
        '
        sed -i "/<\/body>/ $script" ./dist/index.html

    - name: Commit gh-pages
      run: |
        cd $BUILD_PATH
        git init
        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        git status
        git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
        git checkout -b gh-pages
        git add --all
        git commit -m "deploy to Github pages"
        git push origin gh-pages -f
        echo 🤘 deploy gh-pages complete.

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/node_modules/"
